# Configuration for Alacritty, the GPU enhanced terminal emulator.
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

env:
  TERM: xterm-256color

# Window Settings
window:
  dimensions:
    columns: 319
    lines: 84
  padding:
    x: 4
    y: 4
  opacity: 0.8
  dynamic_title: true

# Scrolling Settings
scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  normal:
    family: "Monaco"
  bold:
    family: "Monaco"
  italic:
    family: "Monaco"
  size: 14

# The 'Dark dimmed' colorscheme from Github.
colors:
  primary:
    background: '#2d333b'
    foreground: '#adbac7'
  normal:
    black:   '#2d333b'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
    white:   '#adbac7'
  bright:
    black:   '#768390'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
    white:   '#adbac7'
